#!/usr/bin/env bash
# PreToolUse guard wrapper: resolve the owning jaunt project from the tool-call
# payload path, then run `jaunt guard` from there so generated_dir comes from
# the RIGHT config. Fail-open: any env problem exits 0 (never blocks editing).
set -u
uv_cache="${UV_CACHE_DIR:-${PLUGIN_DATA:-${CLAUDE_PLUGIN_DATA:-${TMPDIR:-/tmp}/jaunt-plugin-uv-cache-${UID:-user}}}}"

# Resolve an available timeout wrapper: GNU `timeout`, Homebrew `gtimeout`, or
# neither (stock macOS) — in which case run the command with no timeout at all
# rather than 127ing and mis-reporting the tool as missing.
if command -v timeout >/dev/null 2>&1; then
  _timeout_bin=timeout
elif command -v gtimeout >/dev/null 2>&1; then
  _timeout_bin=gtimeout
else
  _timeout_bin=""
fi
run_timeout() {
  local secs="$1"
  shift
  if [ -n "$_timeout_bin" ]; then
    "$_timeout_bin" "$secs" "$@"
  else
    "$@"
  fi
}
has_uv_project() {
  local candidate="$1"
  while [ "$candidate" != "/" ]; do
    if [ -f "$candidate/pyproject.toml" ] || [ -f "$candidate/uv.lock" ]; then
      return 0
    fi
    candidate=$(dirname "$candidate")
  done
  return 1
}
minimum_jaunt_version() {
  python3 -c '
import sys, tomllib
try:
    with open(sys.argv[1], "rb") as handle:
        version = tomllib.load(handle).get("version")
except Exception:
    version = 2
print("1.7.0" if version == 2 else "1.6.2")
' "$1/jaunt.toml" 2>/dev/null
}
version_is_compatible() {
  local minimum
  minimum=$(minimum_jaunt_version "$2") || return 1
  python3 - "$1" "$minimum" <<'PY' >/dev/null 2>&1
import re, sys
match = re.search(r"(?<![0-9])(\d+)\.(\d+)\.(\d+)", sys.argv[1])
minimum = tuple(int(part) for part in sys.argv[2].split("."))
raise SystemExit(0 if match and tuple(map(int, match.groups())) >= minimum else 1)
PY
}
compatible_path_jaunt() {
  local output
  output=$(jaunt --version 2>/dev/null) || return 1
  version_is_compatible "$output" "$1"
}
compatible_uv_jaunt() {
  local dir="$1"
  local output
  output=$(
    cd "$dir" &&
      UV_CACHE_DIR="$uv_cache" run_timeout 8 uv run --no-sync jaunt --version 2>/dev/null
  ) || return 1
  version_is_compatible "$output" "$1"
}

payload=$(cat 2>/dev/null) || exit 0
[ -z "$payload" ] && exit 0

path=$(printf '%s' "$payload" | python3 -c '
import json, sys
try:
    p = json.load(sys.stdin)
except Exception:
    sys.exit(0)
ti = p.get("tool_input") or {}
for k in ("file_path", "path", "notebook_path"):
    v = ti.get(k)
    if v:
        print(v)
        break
' 2>/dev/null) || exit 0
[ -z "$path" ] && exit 0

dir=$(dirname "$path" 2>/dev/null) || exit 0
case "$dir" in /*) ;; *) dir="${CLAUDE_PROJECT_DIR:-$PWD}/$dir" ;; esac
case "$path" in /*) ;; *) path="${CLAUDE_PROJECT_DIR:-$PWD}/$path" ;; esac
while [ -n "$dir" ] && [ "$dir" != "/" ]; do
  [ -f "$dir/jaunt.toml" ] && break
  dir=$(dirname "$dir")
done
[ -f "$dir/jaunt.toml" ] || exit 0

# Jaunt's generated .pyi files sit beside the source spec rather than inside
# generated_dir, so the core guard cannot identify them by path alone.
if [ -f "$path" ] && [ "${path##*.}" = "pyi" ] && \
  head -n 8 "$path" 2>/dev/null | grep -Fq '# This .pyi stub was generated by jaunt. DO NOT EDIT.'; then
  spec="${path%.pyi}.py"
  python3 -c '
import json, sys
path, spec = sys.argv[1:]
reason = (
    f"{path} is a Jaunt-generated provenance stub. Edit the spec instead: "
    f"{spec}. Rebuild to re-emit the .pyi file."
)
print(json.dumps({"hookSpecificOutput": {
    "hookEventName": "PreToolUse",
    "permissionDecision": "ask",
    "permissionDecisionReason": reason,
}}))
' "$path" "$spec" 2>/dev/null || true
  exit 0
fi

cd "$dir" 2>/dev/null || exit 0
# `jaunt guard` resolves generated_dir from the payload's `cwd` when present
# (Claude Code sets it to the SESSION cwd), which would defeat the owning-
# project cd above. Rewrite cwd to the owning project so the right config wins.
payload=$(printf '%s' "$payload" | python3 -c '
import json, sys
p = json.load(sys.stdin)
p["cwd"] = sys.argv[1]
print(json.dumps(p))
' "$dir" 2>/dev/null) || exit 0
[ -z "$payload" ] && exit 0
# A jaunt on PATH may be stale (e.g. a version-manager shim for a pre-1.3
# install with no `guard` subcommand). Trust it only when it exits 0;
# otherwise fall back to the project env via uv, then uvx for a JavaScript-only
# workspace.
if command -v jaunt >/dev/null 2>&1 && compatible_path_jaunt "$dir"; then
  out=$(printf '%s' "$payload" | run_timeout 8 jaunt guard 2>/dev/null)
  if [ $? -eq 0 ]; then
    printf '%s' "$out"
    exit 0
  fi
fi
if command -v uv >/dev/null 2>&1 && has_uv_project "$dir" && compatible_uv_jaunt "$dir"; then
  out=$(printf '%s' "$payload" | UV_CACHE_DIR="$uv_cache" run_timeout 8 uv run --no-sync jaunt guard 2>/dev/null)
  if [ $? -eq 0 ]; then
    printf '%s' "$out"
    exit 0
  fi
fi
if command -v uvx >/dev/null 2>&1; then
  printf '%s' "$payload" | UV_CACHE_DIR="$uv_cache" run_timeout 8 uvx jaunt guard 2>/dev/null || true
fi
exit 0
