# This file was generated by jaunt. DO NOT EDIT.
# jaunt:tool_version=1.6.3
# jaunt:kind=build
# jaunt:source_module=jaunt.contract.cases
# jaunt:module_digest=sha256:242da429ca8029321d67540411884b32c1dc6d3925ffbad5fe2d293b80708788
# jaunt:digest_scheme=2
# jaunt:spec_digests={"jaunt.contract.cases:parse_case_blocks": {"p": "05c2d680041959dbec4b464e77d43e970ad80735bf2a129b162a6709de53bd18", "s": "8d892f6dee8e593d5adee4fea3a55d80d2e45e0b997ed7701e560510271ef9fe"}}
# jaunt:generation_fingerprint=sha256:ce5b7955d1d41de6dabe0fc8f7ef796a0c18cad9d8bcc9043d8e4bc2f8ce1306
# jaunt:module_api_digest=sha256:5d67168dcc6ff08169cb3956c296803b357e7aa8c16220019917d2979d831aa9
# jaunt:module_context_digest=sha256:e78c093921140aab0ba7dcc449acf49cc47a4028465587f7c6e21d626a865801
# jaunt:spec_refs=["jaunt.contract.cases:parse_case_blocks"]

from __future__ import annotations

import ast
import re
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from jaunt.contract.cases import CallCase, CaseBlocks

__all__ = ["parse_case_blocks"]


def parse_case_blocks(
    docstring: str,
    *,
    target: str,
    async_map: dict[str, bool],
    module_names: frozenset[str],
    method: str | None = None,
) -> CaseBlocks:
    r"""Parse executable example and exception cases from a spec docstring."""
    from jaunt.contract.cases import (
        _CASE_EXCEPTION_NAME_RE,
        CaseBlocks,
        CaseParseError,
        _call_root_and_method,
        _case_lines_for_section,
        _make_case,
        _parse_fixtures,
        _split_top_level_eq,
        _valid_case_expr,
    )

    fixtures_declared = _parse_fixtures(docstring)
    examples: list[CallCase] = []
    raises: list[CallCase] = []

    for line in _case_lines_for_section(docstring, "Examples"):
        equality = _split_top_level_eq(line)
        if equality is not None:
            call_expr, expected = equality
            tree = ast.parse(call_expr, mode="eval")
            rooted, _ = _call_root_and_method(tree.body, target)
            if not rooted:
                raise CaseParseError(
                    f"example call must be rooted in the target {target!r}",
                    line=line,
                )
            examples.append(
                _make_case(
                    source_line=line,
                    call_expr=call_expr,
                    expected_expr=expected,
                    exc_name=None,
                    legacy=False,
                    target=target,
                    async_map=async_map,
                    fixtures_declared=fixtures_declared,
                    module_names=module_names,
                    method_override=method,
                )
            )
            continue

        if "->" in line:
            left, right = (part.strip() for part in line.split("->", 1))
            if _valid_case_expr(left) and _valid_case_expr(right):
                examples.append(
                    _make_case(
                        source_line=line,
                        call_expr=f"{target}({left})",
                        expected_expr=right,
                        exc_name=None,
                        legacy=True,
                        target=target,
                        async_map=async_map,
                        fixtures_declared=fixtures_declared,
                        module_names=module_names,
                        method_override=method,
                    )
                )

    for line in _case_lines_for_section(docstring, "Raises"):
        if " raises " in line:
            inp, exc = line.split(" raises ", 1)
            inp = inp.strip()
            exc = exc.strip().rstrip(".")
            if not _valid_case_expr(inp) or not _CASE_EXCEPTION_NAME_RE.match(exc):
                continue

            tree = ast.parse(inp, mode="eval")
            rooted, _ = _call_root_and_method(tree.body, target)
            call_form = rooted and isinstance(tree.body, (ast.Call, ast.Attribute))
            raises.append(
                _make_case(
                    source_line=line,
                    call_expr=inp if call_form else f"{target}({inp})",
                    expected_expr=None,
                    exc_name=exc,
                    legacy=not call_form,
                    target=target,
                    async_map=async_map,
                    fixtures_declared=fixtures_declared,
                    module_names=module_names,
                    method_override=method,
                )
            )
            continue

        match = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\s+on\s+(.+)$", line)
        if match is None:
            continue
        exc = match.group(1)
        inp = match.group(2).strip()
        if _valid_case_expr(inp):
            raises.append(
                _make_case(
                    source_line=line,
                    call_expr=f"{target}({inp})",
                    expected_expr=None,
                    exc_name=exc,
                    legacy=True,
                    target=target,
                    async_map=async_map,
                    fixtures_declared=fixtures_declared,
                    module_names=module_names,
                    method_override=method,
                )
            )

    return CaseBlocks(
        examples=tuple(examples),
        raises=tuple(raises),
        fixtures_declared=fixtures_declared,
    )
