# This file was generated by jaunt. DO NOT EDIT.
# jaunt:tool_version=1.6.1
# jaunt:kind=build
# jaunt:source_module=jaunt.contract.cases
# jaunt:module_digest=sha256:b8d59b165363205ccb72b1eaf6b7183de1661af57378d81f346acda64a751b62
# jaunt:digest_scheme=2
# jaunt:spec_digests={"jaunt.contract.cases:parse_case_blocks": {"p": "e71512bca2de7f1343d84af3cf88c9ed1c86862ff51f2a4073e29ac4eab472ce", "s": "8d892f6dee8e593d5adee4fea3a55d80d2e45e0b997ed7701e560510271ef9fe"}}
# jaunt:generation_fingerprint=sha256:ce5b7955d1d41de6dabe0fc8f7ef796a0c18cad9d8bcc9043d8e4bc2f8ce1306
# jaunt:module_api_digest=sha256:328d5e98fb7740a2bc0dfda6bc6caa98869febe73b85f6e3b14339d452063066
# jaunt:module_context_digest=sha256:e78c093921140aab0ba7dcc449acf49cc47a4028465587f7c6e21d626a865801
# jaunt:spec_refs=["jaunt.contract.cases:parse_case_blocks"]

from __future__ import annotations

import ast
import importlib
import re
import sys
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from jaunt.contract.cases import CaseBlocks

__all__ = ["parse_case_blocks"]


def parse_case_blocks(
    docstring: str,
    *,
    target: str,
    async_map: dict[str, bool],
    module_names: frozenset[str],
    method: str | None = None,
) -> CaseBlocks:
    r"""Parse a spec ``docstring`` into executable example and raises cases."""
    cases_module = sys.modules.get("jaunt.contract.cases")
    if cases_module is None:
        cases_module = importlib.import_module("jaunt.contract.cases")

    source_symbols = cases_module.__dict__
    case_lines_for_section = source_symbols["_case_lines_for_section"]
    parse_fixtures = source_symbols["_parse_fixtures"]
    make_case = source_symbols["_make_case"]
    split_top_level_eq = source_symbols["_split_top_level_eq"]
    call_root_and_method = source_symbols["_call_root_and_method"]
    valid_case_expr = source_symbols["_valid_case_expr"]
    exception_name_re = source_symbols["_CASE_EXCEPTION_NAME_RE"]
    case_parse_error = source_symbols["CaseParseError"]
    case_blocks = source_symbols["CaseBlocks"]

    fixtures_declared = parse_fixtures(docstring)
    examples = []
    raises = []

    for line in case_lines_for_section(docstring, "Examples"):
        split = split_top_level_eq(line)
        if split is not None:
            call_expr, expected_expr = split
            rooted, _ = call_root_and_method(ast.parse(call_expr, mode="eval").body, target)
            if not rooted:
                raise case_parse_error(
                    f"example call must be rooted in the target {target!r}",
                    line=line,
                )
            examples.append(
                make_case(
                    source_line=line,
                    call_expr=call_expr,
                    expected_expr=expected_expr,
                    exc_name=None,
                    legacy=False,
                    target=target,
                    async_map=async_map,
                    fixtures_declared=fixtures_declared,
                    module_names=module_names,
                    method_override=method,
                )
            )
            continue

        if "->" not in line:
            continue

        left, right = (part.strip() for part in line.split("->", 1))
        if not valid_case_expr(left) or not valid_case_expr(right):
            continue
        examples.append(
            make_case(
                source_line=line,
                call_expr=f"{target}({left})",
                expected_expr=right,
                exc_name=None,
                legacy=True,
                target=target,
                async_map=async_map,
                fixtures_declared=fixtures_declared,
                module_names=module_names,
                method_override=method,
            )
        )

    for line in case_lines_for_section(docstring, "Raises"):
        if " raises " in line:
            inp, exc = line.split(" raises ", 1)
            inp = inp.strip()
            exc = exc.strip().rstrip(".")
            if not valid_case_expr(inp) or exception_name_re.match(exc) is None:
                continue

            tree = ast.parse(inp, mode="eval")
            rooted, _ = call_root_and_method(tree.body, target)
            if rooted and isinstance(tree.body, ast.Call | ast.Attribute):
                call_expr = inp
                legacy = False
            else:
                call_expr = f"{target}({inp})"
                legacy = True
            raises.append(
                make_case(
                    source_line=line,
                    call_expr=call_expr,
                    expected_expr=None,
                    exc_name=exc,
                    legacy=legacy,
                    target=target,
                    async_map=async_map,
                    fixtures_declared=fixtures_declared,
                    module_names=module_names,
                    method_override=method,
                )
            )
            continue

        match = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\s+on\s+(.+)$", line)
        if match is None:
            continue

        exc = match.group(1)
        inp = match.group(2).strip()
        if not valid_case_expr(inp):
            continue
        raises.append(
            make_case(
                source_line=line,
                call_expr=f"{target}({inp})",
                expected_expr=None,
                exc_name=exc,
                legacy=True,
                target=target,
                async_map=async_map,
                fixtures_declared=fixtures_declared,
                module_names=module_names,
                method_override=method,
            )
        )

    return case_blocks(
        examples=tuple(examples),
        raises=tuple(raises),
        fixtures_declared=fixtures_declared,
    )
