# This file was generated by jaunt. DO NOT EDIT.
# jaunt:tool_version=1.5.1
# jaunt:kind=build
# jaunt:source_module=jaunt.contract.drift
# jaunt:module_digest=sha256:e441e84affeadb4289c04ff175957015f4bb6bbc2f21d970c9a713f7ce376156
# jaunt:digest_scheme=2
# jaunt:spec_digests={"jaunt.contract.drift:compute_drift_state": {"p": "f8604712dc61034827616b6336a1c7f476c3f12a3a40d8fdd6771e260810ee72", "s": "1475034b54412a237b3a8cfa6de3519c2c8c41bdd0591df92b2d25568b7d6d7a"}}
# jaunt:generation_fingerprint=sha256:eb3e1333da7449bf778b85ba678bc29fcd75ee04d27ba64205e37fe6de578a45
# jaunt:module_api_digest=sha256:fc9c99cdf7235eedec71348baa312a3d51194344674e57cb9122e44622377cfe
# jaunt:module_context_digest=sha256:7f7f963d933c6919cfcf8d23ed48996d5daf4edd8dd0efd2cdcafd797acabc5c
# jaunt:spec_refs=["jaunt.contract.drift:compute_drift_state"]

from __future__ import annotations

import importlib
from typing import TYPE_CHECKING, cast

if TYPE_CHECKING:
    from jaunt.contract.drift import DriftState


def _drift_state_type() -> type[DriftState]:
    module = importlib.import_module("jaunt.contract.drift")
    return cast("type[DriftState]", getattr(module, "DriftState"))


def compute_drift_state(
    *,
    has_battery: bool,
    prose_match: bool,
    signature_match: bool,
    body_match: bool,
    battery_passed: bool | None,
) -> DriftState:
    """Resolve the drift state of one contract function from five boolean signals."""
    drift_state = _drift_state_type()

    if not has_battery:
        return drift_state.UNBUILT
    if not prose_match:
        return drift_state.STALE_PROSE
    if not signature_match:
        return drift_state.SIGNATURE_DRIFT
    if battery_passed is False:
        return drift_state.BEHAVIOR_DRIFT
    if not body_match:
        return drift_state.REFACTORED
    return drift_state.IN_SYNC
