# This file was generated by jaunt. DO NOT EDIT.
# jaunt:tool_version=1.6.1
# jaunt:kind=build
# jaunt:source_module=jaunt.contract.edits
# jaunt:module_digest=sha256:19a1e6d6a6ac20c32df11edc6359155e70ca71e7c863546e8043ee3103bbf983
# jaunt:digest_scheme=2
# jaunt:spec_digests={"jaunt.contract.edits:add_contract_marker": {"p": "fd52b444b2ac9d3fe2e9d33d33f3e8906e6e6e3d4efb6a4a29c00b97f09ee487", "s": "f047f8a39deb4aadffdc10c38960a1a96093fd5cef8db08b2d80c4cbf166abf6"}, "jaunt.contract.edits:remove_contract_marker": {"p": "cbbcc72f613b34dd187fbe129fc72d77e79e193e03ab05cdddd9654958b5d90d", "s": "6c9c76d869e2b0244be574de8be219315e449fa7c640aa4f0a21ce21ea758777"}}
# jaunt:generation_fingerprint=sha256:ce5b7955d1d41de6dabe0fc8f7ef796a0c18cad9d8bcc9043d8e4bc2f8ce1306
# jaunt:module_api_digest=sha256:7e1a782b5c96b1778328152254d60b3cea2eb539215e4f4fc353eda87b80f0c7
# jaunt:module_context_digest=sha256:27ad5ace17949f75dff875609753387b8936fbcdb5e213cc5464f63e27049e5a
# jaunt:spec_refs=["jaunt.contract.edits:add_contract_marker", "jaunt.contract.edits:remove_contract_marker"]

from __future__ import annotations

import ast
from collections.abc import Callable
from typing import cast


__all__ = ["add_contract_marker", "remove_contract_marker"]

_TargetNode = ast.FunctionDef | ast.AsyncFunctionDef | ast.ClassDef
_FindTarget = Callable[[str, str], _TargetNode]
_EnsureImportJaunt = Callable[[list[str]], list[str]]


def _source_attribute(name: str) -> object:
    from jaunt.contract import edits

    return getattr(edits, name)


def _find_target_node(source: str, name: str) -> _TargetNode:
    find_target = cast(_FindTarget, _source_attribute("_find_target"))
    return find_target(source, name)


def _ensure_jaunt_import(lines: list[str]) -> list[str]:
    ensure_import = cast(_EnsureImportJaunt, _source_attribute("_ensure_import_jaunt"))
    return ensure_import(lines)


def _decorator_text(decorator: ast.expr) -> str:
    return ast.unparse(decorator)


def _join_preserving_final_newline(lines: list[str], source: str) -> str:
    result = "\n".join(lines)
    if source.endswith("\n"):
        result += "\n"
    return result


def add_contract_marker(source: str, func_name: str) -> str:
    """Add a ``@jaunt.contract`` decorator to a top-level function or class."""
    target = _find_target_node(source, func_name)

    for decorator in target.decorator_list:
        text = _decorator_text(decorator)
        if text in {"jaunt.contract", "jaunt.contract()"} or text.endswith(".contract"):
            return source

    lines = source.splitlines()
    anchor_line = target.decorator_list[0].lineno if target.decorator_list else target.lineno
    anchor_index = anchor_line - 1
    anchor = lines[anchor_index]
    indent = anchor[: len(anchor) - len(anchor.lstrip())]
    lines.insert(anchor_index, f"{indent}@jaunt.contract")
    lines = _ensure_jaunt_import(lines)
    return _join_preserving_final_newline(lines, source)


def remove_contract_marker(source: str, func_name: str) -> str:
    """Remove exact ``@jaunt.contract`` decorators from a top-level target."""
    target = _find_target_node(source, func_name)
    contract_lines = {
        decorator.lineno
        for decorator in target.decorator_list
        if _decorator_text(decorator) in {"jaunt.contract", "jaunt.contract()"}
    }

    if not contract_lines:
        return source

    lines = [
        line for line_number, line in enumerate(source.splitlines(), start=1)
        if line_number not in contract_lines
    ]
    return _join_preserving_final_newline(lines, source)
