# This file was generated by jaunt. DO NOT EDIT.
# jaunt:tool_version=1.6.3
# jaunt:kind=build
# jaunt:source_module=jaunt.contract.edits
# jaunt:module_digest=sha256:19a1e6d6a6ac20c32df11edc6359155e70ca71e7c863546e8043ee3103bbf983
# jaunt:digest_scheme=2
# jaunt:spec_digests={"jaunt.contract.edits:add_contract_marker": {"p": "fd52b444b2ac9d3fe2e9d33d33f3e8906e6e6e3d4efb6a4a29c00b97f09ee487", "s": "f047f8a39deb4aadffdc10c38960a1a96093fd5cef8db08b2d80c4cbf166abf6"}, "jaunt.contract.edits:remove_contract_marker": {"p": "cbbcc72f613b34dd187fbe129fc72d77e79e193e03ab05cdddd9654958b5d90d", "s": "6c9c76d869e2b0244be574de8be219315e449fa7c640aa4f0a21ce21ea758777"}}
# jaunt:generation_fingerprint=sha256:ce5b7955d1d41de6dabe0fc8f7ef796a0c18cad9d8bcc9043d8e4bc2f8ce1306
# jaunt:module_api_digest=sha256:7e1a782b5c96b1778328152254d60b3cea2eb539215e4f4fc353eda87b80f0c7
# jaunt:module_context_digest=sha256:27ad5ace17949f75dff875609753387b8936fbcdb5e213cc5464f63e27049e5a
# jaunt:spec_refs=["jaunt.contract.edits:add_contract_marker", "jaunt.contract.edits:remove_contract_marker"]

import ast

def add_contract_marker(source: str, func_name: str) -> str:
    """Add a ``@jaunt.contract`` decorator to a top-level function or class."""
    from jaunt.contract import edits as source_edits
    target = source_edits._find_target(source, func_name)
    decorator_texts = (ast.unparse(decorator) for decorator in target.decorator_list)
    if any((text in {'jaunt.contract', 'jaunt.contract()'} or text.endswith('.contract') for text in decorator_texts)):
        return source
    anchor_line = target.decorator_list[0].lineno if target.decorator_list else target.lineno
    lines = source.splitlines()
    anchor_index = anchor_line - 1
    anchor = lines[anchor_index]
    indent = anchor[:len(anchor) - len(anchor.lstrip())]
    lines.insert(anchor_index, f'{indent}@jaunt.contract')
    lines = source_edits._ensure_import_jaunt(lines)
    result = '\n'.join(lines)
    if source.endswith('\n'):
        result += '\n'
    return result

def remove_contract_marker(source: str, func_name: str) -> str:
    """Remove exact Jaunt contract decorators from a named top-level definition."""
    from jaunt.contract.edits import _find_target
    target = _find_target(source, func_name)
    decorator_lines = {decorator.lineno for decorator in target.decorator_list if ast.unparse(decorator) in {'jaunt.contract', 'jaunt.contract()'}}
    if not decorator_lines:
        return source
    remaining_lines = [line for line_number, line in enumerate(source.splitlines(), start=1) if line_number not in decorator_lines]
    result = '\n'.join(remaining_lines)
    if source.endswith('\n'):
        result += '\n'
    return result
