# This file was generated by jaunt. DO NOT EDIT.
# jaunt:tool_version=1.6.3
# jaunt:kind=build
# jaunt:source_module=jaunt.contract.strength
# jaunt:module_digest=sha256:6f9f735029a0e75219b40e96c6fc2e3a8e87c0966b8a5879a983825e040c175a
# jaunt:digest_scheme=2
# jaunt:spec_digests={"jaunt.contract.strength:compute_case_strength": {"p": "76a65ec8a8a19600a07b5985853b4c278a7719539405359530f1267169dfb124", "s": "8c1f5c405744d39f8cbfa230b4660175b1b469e4598838c881b8b574ced46b54"}, "jaunt.contract.strength:format_strength": {"p": "6a1e9dfd6c7f1cfe61edd37f71dbe84300bfc4ed1cda56af27bf3d220867b61d", "s": "8ea1d923576cf0ce1fecdb27cb47478ea10be63bed9a728a8e3346725d7aab7c"}, "jaunt.contract.strength:iter_mutants": {"p": "584d506b62e9e4d13ec6eff8d5705e54e48d7e9b0bff8ecd9996836ed8379fcc", "s": "3d1aaa5b6f19c9b5fe15707ca9ae1562a65e56d008369384cf623fecd1ceb166"}, "jaunt.contract.strength:parse_strength": {"p": "3fddb3460e474c0d30ce1962a6441e9acff787341653319f2f7d160d9cf50eb7", "s": "0993d40eac3a951352fe2cf82ebad9ab373c30ac328211d5dc98e1b00a551222"}}
# jaunt:generation_fingerprint=sha256:ce5b7955d1d41de6dabe0fc8f7ef796a0c18cad9d8bcc9043d8e4bc2f8ce1306
# jaunt:module_api_digest=sha256:4935339b6dc2c5b3817cec5e1f86fbebeb6e32e89e33bb3299ad6b309035f229
# jaunt:module_context_digest=sha256:2cc5cd404847c58cc286b6191599da26562c0de0e87ae5dc99f2ae88d6b7e254
# jaunt:spec_refs=["jaunt.contract.strength:compute_case_strength", "jaunt.contract.strength:format_strength", "jaunt.contract.strength:iter_mutants", "jaunt.contract.strength:parse_strength"]

import ast
from collections.abc import Iterator
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from jaunt.contract.cases import CaseBlocks

__all__ = ["compute_case_strength", "format_strength", "iter_mutants", "parse_strength"]


def compute_case_strength(
    source: str,
    target: str,
    blocks: "CaseBlocks",
    namespace: dict[str, object],
) -> tuple[int, int, int]:
    """Score how many generated mutants are killed by the non-fixture cases."""
    import jaunt.contract.strength as strength_module
    from jaunt.contract.cases import CaseBlocks

    excluded = sum(1 for case in blocks.examples if case.fixtures)
    excluded += sum(1 for case in blocks.raises if case.fixtures)
    pure = CaseBlocks(
        examples=tuple(case for case in blocks.examples if not case.fixtures),
        raises=tuple(case for case in blocks.raises if not case.fixtures),
        fixtures_declared=blocks.fixtures_declared,
    )

    if pure.is_empty():
        applicable = sum(1 for _mutant_source in iter_mutants(source))
        return 0, applicable, excluded

    killed = 0
    applicable = 0
    for mutant_source in iter_mutants(source):
        mutant_namespace = dict(namespace)
        try:
            code = compile(mutant_source, "<mutant>", "exec")
            exec(code, mutant_namespace)
        except Exception:
            continue

        if not callable(mutant_namespace.get(target)):
            continue

        applicable += 1
        if strength_module._evaluate_mutant_killed(pure, mutant_namespace):
            killed += 1

    return killed, applicable, excluded


def format_strength(killed: int, applicable: int) -> str:
    """Format killed and applicable mutant counts as a strength string."""
    return f"{killed}/{applicable}"


def iter_mutants(func_source: str) -> Iterator[str]:
    """Yield each one-mutation variant emitted by the handwritten helpers."""
    import jaunt.contract.strength as strength_module

    base = ast.parse(func_source)
    skip = strength_module._skip_constant_ids(base)
    nodes = strength_module._mutation_targets(base)

    for index, node in enumerate(nodes):
        yield from strength_module._mutate_node(base, index, node, skip)

    for walk_index, statement_index in strength_module._stmt_deletion_targets(base):
        mutant_source = strength_module._emit_stmt_deletion(base, walk_index, statement_index)
        if mutant_source is not None:
            yield mutant_source


def parse_strength(text: str) -> tuple[int, int]:
    """Parse a killed/applicable strength string, returning zeroes if invalid."""
    killed_text, _separator, applicable_text = text.partition("/")
    try:
        return int(killed_text), int(applicable_text)
    except ValueError:
        return 0, 0
