# This file was generated by jaunt. DO NOT EDIT.
# jaunt:tool_version=1.5.2
# jaunt:kind=build
# jaunt:source_module=jaunt.contract.strength
# jaunt:module_digest=sha256:6f9f735029a0e75219b40e96c6fc2e3a8e87c0966b8a5879a983825e040c175a
# jaunt:digest_scheme=2
# jaunt:spec_digests={"jaunt.contract.strength:compute_case_strength": {"p": "76a65ec8a8a19600a07b5985853b4c278a7719539405359530f1267169dfb124", "s": "8c1f5c405744d39f8cbfa230b4660175b1b469e4598838c881b8b574ced46b54"}, "jaunt.contract.strength:format_strength": {"p": "6a1e9dfd6c7f1cfe61edd37f71dbe84300bfc4ed1cda56af27bf3d220867b61d", "s": "8ea1d923576cf0ce1fecdb27cb47478ea10be63bed9a728a8e3346725d7aab7c"}, "jaunt.contract.strength:iter_mutants": {"p": "584d506b62e9e4d13ec6eff8d5705e54e48d7e9b0bff8ecd9996836ed8379fcc", "s": "3d1aaa5b6f19c9b5fe15707ca9ae1562a65e56d008369384cf623fecd1ceb166"}, "jaunt.contract.strength:parse_strength": {"p": "3fddb3460e474c0d30ce1962a6441e9acff787341653319f2f7d160d9cf50eb7", "s": "0993d40eac3a951352fe2cf82ebad9ab373c30ac328211d5dc98e1b00a551222"}}
# jaunt:generation_fingerprint=sha256:eb3e1333da7449bf778b85ba678bc29fcd75ee04d27ba64205e37fe6de578a45
# jaunt:module_api_digest=sha256:4935339b6dc2c5b3817cec5e1f86fbebeb6e32e89e33bb3299ad6b309035f229
# jaunt:module_context_digest=sha256:2cc5cd404847c58cc286b6191599da26562c0de0e87ae5dc99f2ae88d6b7e254
# jaunt:spec_refs=["jaunt.contract.strength:compute_case_strength", "jaunt.contract.strength:format_strength", "jaunt.contract.strength:iter_mutants", "jaunt.contract.strength:parse_strength"]

from __future__ import annotations

import ast
from collections.abc import Callable, Iterator
from typing import TYPE_CHECKING, cast

if TYPE_CHECKING:
    from jaunt.contract.cases import CaseBlocks

__all__ = [
    "compute_case_strength",
    "format_strength",
    "iter_mutants",
    "parse_strength",
]


def compute_case_strength(
    source: str,
    target: str,
    blocks: "CaseBlocks",
    namespace: dict[str, object],
) -> tuple[int, int, int]:
    """Score how many mutants of ``source`` the contract cases in ``blocks`` kill."""

    from jaunt.contract.cases import CaseBlocks
    import jaunt.contract.strength as strength_module

    pure_examples = tuple(case for case in blocks.examples if not case.fixtures)
    pure_raises = tuple(case for case in blocks.raises if not case.fixtures)
    excluded = sum(1 for case in blocks.examples if case.fixtures) + sum(
        1 for case in blocks.raises if case.fixtures
    )
    pure = CaseBlocks(
        examples=pure_examples,
        raises=pure_raises,
        fixtures_declared=blocks.fixtures_declared,
    )

    if pure.is_empty():
        applicable = sum(1 for _mutant_src in iter_mutants(source))
        return (0, applicable, excluded)

    evaluate_mutant_killed = cast(
        Callable[[CaseBlocks, dict[str, object]], bool],
        getattr(strength_module, "_evaluate_mutant_killed"),
    )

    killed = 0
    applicable = 0
    for mutant_src in iter_mutants(source):
        ns = dict(namespace)
        try:
            exec(compile(mutant_src, "<mutant>", "exec"), ns)
        except Exception:
            continue
        if not callable(ns.get(target)):
            continue
        applicable += 1
        if evaluate_mutant_killed(pure, ns):
            killed += 1

    return (killed, applicable, excluded)


def format_strength(killed: int, applicable: int) -> str:
    """Format a strength pair as the ``"<killed>/<applicable>"`` string."""

    return f"{killed}/{applicable}"


def iter_mutants(func_source: str) -> Iterator[str]:
    """Yield one-mutation variants of ``func_source`` as unparsed Python source."""

    import jaunt.contract.strength as strength_module

    mutation_targets = cast(
        Callable[[ast.Module], list[ast.AST]],
        getattr(strength_module, "_mutation_targets"),
    )
    skip_constant_ids = cast(
        Callable[[ast.Module], set[int]],
        getattr(strength_module, "_skip_constant_ids"),
    )
    mutate_node = cast(
        Callable[[ast.Module, int, ast.AST, set[int]], Iterator[str]],
        getattr(strength_module, "_mutate_node"),
    )
    stmt_deletion_targets = cast(
        Callable[[ast.Module], list[tuple[int, int]]],
        getattr(strength_module, "_stmt_deletion_targets"),
    )
    emit_stmt_deletion = cast(
        Callable[[ast.Module, int, int], str | None],
        getattr(strength_module, "_emit_stmt_deletion"),
    )

    base = ast.parse(func_source)
    skip = skip_constant_ids(base)
    nodes = mutation_targets(base)

    for index, node in enumerate(nodes):
        yield from mutate_node(base, index, node, skip)

    for walk_index, stmt_index in stmt_deletion_targets(base):
        deleted = emit_stmt_deletion(base, walk_index, stmt_index)
        if deleted is not None:
            yield deleted


def parse_strength(text: str) -> tuple[int, int]:
    """Parse a ``"<killed>/<applicable>"`` strength string into ``(killed, applicable)``."""

    killed_text, separator, applicable_text = text.partition("/")
    if separator == "":
        applicable_text = ""
    try:
        return (int(killed_text), int(applicable_text))
    except ValueError:
        return (0, 0)
