# This .pyi stub was generated by jaunt. DO NOT EDIT.
# jaunt:tool_version=1.6.3
# jaunt:kind=stub
# jaunt:source_module=jaunt.guard
# jaunt:generated_digest=sha256:cb84723a66195c1ecbae41e62c070774dc68833ed9b2df59168108b6a0e30f09
# jaunt:inputs_digest=sha256:06c785db3451a5d275406c8ee7b762faf0828e71f38c9eb143efe3d72fea4761

_FILE_KEYS = ("file_path", "path", "notebook_path")

_FILE_TOOLS = frozenset({"Edit", "Write", "Read", "NotebookEdit", "MultiEdit"})

def _owning_spec_hint(path: str, generated_dir: str) -> str: ...
def evaluate(payload: dict, *, generated_dir: str) -> dict | None: ...
