# This .pyi stub was generated by jaunt. DO NOT EDIT.
# jaunt:tool_version=1.7.0
# jaunt:kind=stub
# jaunt:source_module=jaunt.guard
# jaunt:generated_digest=sha256:cb84723a66195c1ecbae41e62c070774dc68833ed9b2df59168108b6a0e30f09
# jaunt:inputs_digest=sha256:5aaffe705a7a7487e48f034f8e64e29fc140730dd7b6edd38c474c9e9bc5861c

_FILE_KEYS = ("file_path", "path", "notebook_path")

_FILE_TOOLS = frozenset({"Edit", "Write", "Read", "NotebookEdit", "MultiEdit"})

def _owning_spec_hint(path: str, generated_dir: str) -> str: ...
def evaluate(payload: dict, *, generated_dir: str) -> dict | None: ...
