# This .pyi stub was generated by jaunt. DO NOT EDIT.
# jaunt:tool_version=1.7.2
# jaunt:kind=stub
# jaunt:source_module=jaunt.guard
# jaunt:generated_digest=sha256:cb84723a66195c1ecbae41e62c070774dc68833ed9b2df59168108b6a0e30f09
# jaunt:inputs_digest=sha256:fe6d980e61f3fe96bb9926f5e151827967aac39e96b1e97487f6560eb2fd3d56
# jaunt:rendered_digest=sha256:79971494521614d1074b97062ab56c99c387de8802d613be24b454c590554d31

_FILE_KEYS = ("file_path", "path", "notebook_path")

_FILE_TOOLS = frozenset({"Edit", "Write", "Read", "NotebookEdit", "MultiEdit"})

def _owning_spec_hint(path: str, generated_dir: str) -> str: ...
def evaluate(payload: dict, *, generated_dir: str) -> dict | None: ...
