"""Generated file header formatting/parsing for Jaunt."""

from __future__ import annotations

import json
from typing import Literal

HEADER_MARKER = "# This file was generated by jaunt. DO NOT EDIT."

CONTRACT_BATTERY_MARKER = (
    "# This contract test battery was derived by jaunt. "
    "Derived regions are regenerated; edits outside them are preserved."
)


def format_contract_battery_header(
    *,
    derived_from: str,
    prose_digest: str,
    signature: str,
    body_digest: str,
    strength: str,
    tool_version: str,
) -> str:
    """Format the header for a committed contract test battery.

    Digest fields are normalized to a ``sha256:`` prefix. Keys are emitted with
    hyphenated names (e.g. ``derived-from``, ``body-digest``).
    """

    prose = prose_digest if prose_digest.startswith("sha256:") else f"sha256:{prose_digest}"
    body = body_digest if body_digest.startswith("sha256:") else f"sha256:{body_digest}"
    lines = [
        CONTRACT_BATTERY_MARKER,
        f"# jaunt:derived-from={derived_from}",
        f"# jaunt:prose-digest={prose}",
        f"# jaunt:signature={signature}",
        f"# jaunt:body-digest={body}",
        f"# jaunt:strength={strength}",
        f"# jaunt:tool-version={tool_version}",
    ]
    return "\n".join(lines) + "\n"


def parse_contract_battery_header(source: str) -> dict[str, str] | None:
    """Parse the contract battery header from the start of a file.

    Returns None if the file does not begin with the contract battery marker.
    Keys are hyphenated (e.g. ``derived-from``, ``body-digest``); digest values
    retain their ``sha256:`` prefix.
    """

    lines = source.splitlines()
    if not lines:
        return None
    if lines[0] != CONTRACT_BATTERY_MARKER:
        return None

    out: dict[str, str] = {}
    for line in lines[1:]:
        if not line.startswith("# jaunt:"):
            break
        rest = line[len("# jaunt:") :]
        if "=" not in rest:
            continue
        key, value = rest.split("=", 1)
        out[key.strip()] = value.strip()
    return out


def format_header(
    *,
    tool_version: str,
    kind: Literal["build", "test"],
    source_module: str,
    module_digest: str,
    generation_fingerprint: str = "",
    module_context_digest: str = "",
    module_api_digest: str = "",
    spec_refs: list[str],
    digest_scheme: int = 1,
    spec_digests: dict[str, dict[str, str]] | None = None,
) -> str:
    digest = module_digest if module_digest.startswith("sha256:") else f"sha256:{module_digest}"
    spec_refs_json = json.dumps(spec_refs, ensure_ascii=True)
    lines = [
        HEADER_MARKER,
        f"# jaunt:tool_version={tool_version}",
        f"# jaunt:kind={kind}",
        f"# jaunt:source_module={source_module}",
        f"# jaunt:module_digest={digest}",
        f"# jaunt:spec_refs={spec_refs_json}",
    ]
    if spec_digests is not None:
        spec_digests_json = json.dumps(spec_digests, ensure_ascii=True, sort_keys=True)
        lines.insert(5, f"# jaunt:spec_digests={spec_digests_json}")
        lines.insert(5, f"# jaunt:digest_scheme={digest_scheme}")
    optional_insert_at = 7 if spec_digests is not None else 5
    if module_context_digest:
        context_digest = (
            module_context_digest
            if module_context_digest.startswith("sha256:")
            else f"sha256:{module_context_digest}"
        )
        lines.insert(optional_insert_at, f"# jaunt:module_context_digest={context_digest}")
    if module_api_digest:
        api_digest = (
            module_api_digest
            if module_api_digest.startswith("sha256:")
            else f"sha256:{module_api_digest}"
        )
        lines.insert(optional_insert_at, f"# jaunt:module_api_digest={api_digest}")
    if generation_fingerprint:
        fingerprint = (
            generation_fingerprint
            if generation_fingerprint.startswith("sha256:")
            else f"sha256:{generation_fingerprint}"
        )
        lines.insert(optional_insert_at, f"# jaunt:generation_fingerprint={fingerprint}")
    return "\n".join(lines) + "\n"


def parse_header(source: str) -> dict[str, str] | None:
    """Parse the Jaunt header from the start of a file.

    Returns None if the file does not begin with the Jaunt header marker.
    """

    lines = source.splitlines()
    if not lines:
        return None
    if lines[0] != HEADER_MARKER:
        return None

    out: dict[str, str] = {}
    for line in lines[1:]:
        if not line.startswith("# jaunt:"):
            break
        rest = line[len("# jaunt:") :]
        if "=" not in rest:
            continue
        key, value = rest.split("=", 1)
        out[key.strip()] = value.strip()
    return out


def extract_module_digest(source: str) -> str | None:
    parsed = parse_header(source)
    if parsed is None:
        return None
    return parsed.get("module_digest")


def extract_generation_fingerprint(source: str) -> str | None:
    parsed = parse_header(source)
    if parsed is None:
        return None
    return parsed.get("generation_fingerprint")


def extract_module_context_digest(source: str) -> str | None:
    parsed = parse_header(source)
    if parsed is None:
        return None
    return parsed.get("module_context_digest")


def extract_module_api_digest(source: str) -> str | None:
    parsed = parse_header(source)
    if parsed is None:
        return None
    return parsed.get("module_api_digest")


def extract_digest_scheme(source: str) -> int | None:
    parsed = parse_header(source)
    if parsed is None:
        return None
    raw = parsed.get("digest_scheme")
    if raw is None:
        return None
    try:
        return int(raw)
    except ValueError:
        return None


def extract_spec_digests(source: str) -> dict[str, dict[str, str]] | None:
    parsed = parse_header(source)
    if parsed is None:
        return None
    raw = parsed.get("spec_digests")
    if raw is None:
        return None
    try:
        value = json.loads(raw)
    except (ValueError, TypeError):
        return None
    if not isinstance(value, dict):
        return None
    return value
