# This .pyi stub was generated by jaunt. DO NOT EDIT.
# jaunt:tool_version=1.5.1
# jaunt:kind=stub
# jaunt:source_module=jaunt.migrate
# jaunt:generated_digest=sha256:4bb5f44a38f8a6a3203cd8373519a225eaceb2798cd0bd51643a8e69e20f81b3
# jaunt:inputs_digest=sha256:8fc9abd911baaf2010e3ed80093cfcca9c57a321e8ff1c9344b25d5aea73fa35

import ast
from dataclasses import dataclass
from pathlib import Path
from typing import Literal
from typing import Any

FunctionNode = Any
body = Any
governs = Any
newly = Any
re = Any
reemit = Any
rewrite = Any
stamp = Any
stub = Any

LEGACY_STUB_MIGRATION_ID = "legacy-stub-body"

STUB_REEMIT_MIGRATION_ID = "stub-reemit"

@dataclass(frozen=True, slots=True)
class MigrationAction:
    migration_id: str
    path: Path
    module: str
    symbol: str
    kind: Literal["rewrite-stub-body", "reemit-stub"]
    classification: Literal["re-stamp", "newly-governs"]
    description: str

def plan_legacy_stub_rewrites(
    *, source_file: Path, module: str, governed_symbols: set[str]
) -> list[MigrationAction]: ...
def _symbol_is_governed(symbol: str, governed_symbols: set[str]) -> bool: ...
def plan_stub_reemissions(
    *, module_specs: dict[str, list], package_dir: Path, generated_dir: str
) -> list[MigrationAction]: ...
def apply_stub_rewrite(action: MigrationAction) -> None: ...
def _iter_rewritable_nodes(tree: ast.Module) -> list[tuple[str, FunctionNode]]: ...
def _is_legacy_stub_node(node: FunctionNode) -> bool: ...
def _is_docstring_expr(node: ast.stmt) -> bool: ...
def _stub_raise(node: FunctionNode) -> ast.Raise: ...
def _line_ending(line: str) -> str: ...
