# This .pyi stub was generated by jaunt. DO NOT EDIT.
# jaunt:tool_version=1.7.2
# jaunt:kind=stub
# jaunt:source_module=jaunt.migrate
# jaunt:generated_digest=sha256:0a1c11f5324101d81a92d3cc588246701570f12514566b1ffc9a74cdb0fee1d4
# jaunt:inputs_digest=sha256:c4d521467b401f2c139f6fc634f83e6140e5139859f3b93cd53f0df7f2058dd7
# jaunt:rendered_digest=sha256:4676f89ada25636362769a8512677adce9dc25a0733d307f93981d550509680f

import ast
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal

FunctionNode = Any
body = Any
governs = Any
newly = Any
re = Any
reemit = Any
rewrite = Any
stamp = Any
stub = Any

LEGACY_STUB_MIGRATION_ID = "legacy-stub-body"

STUB_REEMIT_MIGRATION_ID = "stub-reemit"

@dataclass(frozen=True, slots=True)
class MigrationAction:
    migration_id: str
    path: Path
    module: str
    symbol: str
    kind: Literal["rewrite-stub-body", "reemit-stub"]
    classification: Literal["re-stamp", "newly-governs"]
    description: str

def plan_legacy_stub_rewrites(
    *, source_file: Path, module: str, governed_symbols: set[str]
) -> list[MigrationAction]: ...
def _symbol_is_governed(symbol: str, governed_symbols: set[str]) -> bool: ...
def plan_stub_reemissions(
    *, module_specs: dict[str, list], package_dir: Path, generated_dir: str
) -> list[MigrationAction]: ...
def apply_stub_rewrite(action: MigrationAction) -> None: ...
def _iter_rewritable_nodes(tree: ast.Module) -> list[tuple[str, FunctionNode]]: ...
def _is_legacy_stub_node(node: FunctionNode) -> bool: ...
def _is_docstring_expr(node: ast.stmt) -> bool: ...
def _stub_raise(node: FunctionNode) -> ast.Raise: ...
def _line_ending(line: str) -> str: ...
