#!/usr/bin/env bash
# Codex PreToolUse adapter for apply_patch. Extract every changed path, resolve
# it against payload cwd, and ask Jaunt's core guard whether it is generated.
# Codex does not support permissionDecision=ask, so guarded edits are denied.
# Malformed input, missing config/tools, and timeouts all fail open.
set -u
uv_cache="${UV_CACHE_DIR:-${PLUGIN_DATA:-${CLAUDE_PLUGIN_DATA:-${TMPDIR:-/tmp}/jaunt-plugin-uv-cache-${UID:-user}}}}"

if command -v timeout >/dev/null 2>&1; then
  _timeout_bin=timeout
elif command -v gtimeout >/dev/null 2>&1; then
  _timeout_bin=gtimeout
else
  _timeout_bin=""
fi
run_timeout() {
  local secs="$1"
  shift
  if [ -n "$_timeout_bin" ]; then
    "$_timeout_bin" "$secs" "$@"
  else
    "$@"
  fi
}
has_uv_project() {
  local candidate="$1"
  while [ "$candidate" != "/" ]; do
    if [ -f "$candidate/pyproject.toml" ] || [ -f "$candidate/uv.lock" ]; then
      return 0
    fi
    candidate=$(dirname "$candidate")
  done
  return 1
}
minimum_jaunt_version() {
  python3 -c '
import sys, tomllib
try:
    with open(sys.argv[1], "rb") as handle:
        version = tomllib.load(handle).get("version")
except Exception:
    version = 2
print("1.7.0" if version == 2 else "1.6.2")
' "$1/jaunt.toml" 2>/dev/null
}
version_is_compatible() {
  local minimum
  minimum=$(minimum_jaunt_version "$2") || return 1
  python3 - "$1" "$minimum" <<'PY' >/dev/null 2>&1
import re, sys
match = re.search(r"(?<![0-9])(\d+)\.(\d+)\.(\d+)", sys.argv[1])
minimum = tuple(int(part) for part in sys.argv[2].split("."))
raise SystemExit(0 if match and tuple(map(int, match.groups())) >= minimum else 1)
PY
}
compatible_path_jaunt() {
  local output
  output=$(jaunt --version 2>/dev/null) || return 1
  version_is_compatible "$output" "$1"
}
compatible_uv_jaunt() {
  local dir="$1"
  local output
  output=$(
    cd "$dir" &&
      UV_CACHE_DIR="$uv_cache" run_timeout 8 uv run --no-sync jaunt --version 2>/dev/null
  ) || return 1
  version_is_compatible "$output" "$1"
}

payload=$(cat 2>/dev/null) || exit 0
[ -n "$payload" ] || exit 0
parsed=$(printf '%s' "$payload" | python3 -c '
import json, re, sys
try:
    payload = json.load(sys.stdin)
except Exception:
    sys.exit(0)
if not isinstance(payload, dict) or payload.get("tool_name") != "apply_patch":
    sys.exit(0)
tool_input = payload.get("tool_input")
command = tool_input.get("command") if isinstance(tool_input, dict) else None
cwd = payload.get("cwd")
if not isinstance(command, str) or not isinstance(cwd, str) or not cwd:
    sys.exit(0)
paths = []
for line in command.splitlines():
    match = re.match(r"^\s*\*\*\* (?:Add|Update|Delete) File:\s*(.*?)\s*$", line)
    if match is None:
        match = re.match(r"^\s*\*\*\* Move to:\s*(.*?)\s*$", line)
    if match is not None and match.group(1):
        paths.append(match.group(1))
print(cwd)
for path in dict.fromkeys(paths):
    print(path)
' 2>/dev/null) || exit 0
[ -n "$parsed" ] || exit 0
cwd=$(printf '%s\n' "$parsed" | sed -n '1p')
paths=$(printf '%s\n' "$parsed" | sed '1d')
[ -n "$cwd" ] && [ -n "$paths" ] || exit 0

while IFS= read -r raw_path; do
  [ -n "$raw_path" ] || continue
  case "$raw_path" in /*) path="$raw_path" ;; *) path="$cwd/$raw_path" ;; esac
  path=$(python3 -c 'from pathlib import Path; import sys; print(Path(sys.argv[1]).resolve())' "$path" 2>/dev/null) || continue
  dir=$(dirname "$path" 2>/dev/null) || continue
  while [ -n "$dir" ] && [ "$dir" != "/" ]; do
    [ -f "$dir/jaunt.toml" ] && break
    dir=$(dirname "$dir")
  done
  [ -f "$dir/jaunt.toml" ] || continue

  if [ -f "$path" ] && [ "${path##*.}" = "pyi" ] && \
    head -n 8 "$path" 2>/dev/null | grep -Fq '# This .pyi stub was generated by jaunt. DO NOT EDIT.'; then
    spec="${path%.pyi}.py"
    python3 -c '
import json, sys
path, spec = sys.argv[1:]
reason = (
    f"{path} is a Jaunt-generated provenance stub. Edit the spec instead: "
    f"{spec}. Rebuild to re-emit the .pyi file."
)
print(json.dumps({"hookSpecificOutput": {
    "hookEventName": "PreToolUse",
    "permissionDecision": "deny",
    "permissionDecisionReason": reason,
}}))
' "$path" "$spec" 2>/dev/null || true
    exit 0
  fi

  adapted=$(python3 -c '
import json, sys
print(json.dumps({"tool_name": "Edit", "tool_input": {"file_path": sys.argv[1]}, "cwd": sys.argv[2]}))
' "$path" "$dir" 2>/dev/null) || continue
  out=""
  status=1
  if command -v jaunt >/dev/null 2>&1 && compatible_path_jaunt "$dir"; then
    out=$(printf '%s' "$adapted" | (cd "$dir" && run_timeout 8 jaunt guard) 2>/dev/null)
    status=$?
  fi
  if [ "$status" -ne 0 ] && command -v uv >/dev/null 2>&1 && \
    has_uv_project "$dir" && compatible_uv_jaunt "$dir"; then
    out=$(printf '%s' "$adapted" | (cd "$dir" && UV_CACHE_DIR="$uv_cache" run_timeout 8 uv run --no-sync jaunt guard) 2>/dev/null)
    status=$?
  fi
  if [ "$status" -ne 0 ] && command -v uvx >/dev/null 2>&1; then
    out=$(printf '%s' "$adapted" | (cd "$dir" && UV_CACHE_DIR="$uv_cache" run_timeout 8 uvx jaunt guard) 2>/dev/null)
    status=$?
  fi
  [ "$status" -eq 0 ] || continue
  denied=$(printf '%s' "$out" | python3 -c '
import json, sys
try:
    result = json.load(sys.stdin)
    specific = result.get("hookSpecificOutput")
    if not isinstance(specific, dict):
        raise ValueError
    if specific.get("permissionDecision") not in {"ask", "deny"}:
        raise ValueError
    reason = specific.get("permissionDecisionReason")
    if not isinstance(reason, str) or not reason:
        raise ValueError
    specific["hookEventName"] = "PreToolUse"
    specific["permissionDecision"] = "deny"
    print(json.dumps({"hookSpecificOutput": specific}))
except Exception:
    pass
' 2>/dev/null || true)
  if [ -n "$denied" ]; then
    printf '%s\n' "$denied"
    exit 0
  fi
done <<<"$paths"

exit 0
