# This file was generated by jaunt. DO NOT EDIT.
# jaunt:tool_version=1.6.3
# jaunt:kind=build
# jaunt:source_module=jaunt.guard
# jaunt:module_digest=sha256:6ed105c48ced5ad93b9fdc6b0e15533230e68014fc258db291972d8394c79381
# jaunt:digest_scheme=2
# jaunt:spec_digests={"jaunt.guard:evaluate": {"p": "b328acde17b08cb8f461d6ddf7e9d69c253c37ae92d0f90b0a28414729a642fd", "s": "b21c9b493057604c9c2ff9f9faf75c8a736f81c27f97eaf8d9ed01515ba1cc7f"}}
# jaunt:generation_fingerprint=sha256:ce5b7955d1d41de6dabe0fc8f7ef796a0c18cad9d8bcc9043d8e4bc2f8ce1306
# jaunt:module_api_digest=sha256:b1b402c8e28f5096dcd1b6cff9838c57bdbcdcf2cb098ba13da2b4c5a3fabc4c
# jaunt:module_context_digest=sha256:e8321981aeb93cc5ae56dbb8712bf908f057eb4e7f7d6aa654a46176a021f26d
# jaunt:spec_refs=["jaunt.guard:evaluate"]

def evaluate(payload: dict, *, generated_dir: str) -> dict | None:
    """Decide whether a PreToolUse tool call touches generated code."""
    from jaunt import guard as source_guard

    try:
        tool_name = payload.get("tool_name")
        if tool_name not in source_guard._FILE_TOOLS:
            return None

        tool_input = payload.get("tool_input") or {}
        path = None
        for key in source_guard._FILE_KEYS:
            value = tool_input.get(key)
            if value:
                path = str(value)
                break
    except (AttributeError, TypeError):
        return None

    if not path or not generated_dir:
        return None
    if f"/{generated_dir}/" not in f"/{path}":
        return None

    spec_hint = source_guard._owning_spec_hint(path, generated_dir)
    message = (
        f"{path} is machine-owned generated code (jaunt). Edit the spec instead: "
        f"{spec_hint}. Changes here are overwritten on the next build."
    )
    return {
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "ask",
            "permissionDecisionReason": message,
        }
    }
