# This file was generated by jaunt. DO NOT EDIT.
# jaunt:tool_version=1.6.3
# jaunt:kind=build
# jaunt:source_module=jaunt.heldout
# jaunt:module_digest=sha256:8c1b9c62a3abf2408b0d87bfd720bcbe85ddebc60b5dccb4dcd47f5d51ff38f5
# jaunt:digest_scheme=2
# jaunt:spec_digests={"jaunt.heldout:assign_opaque_ids": {"p": "57ef7511b6b708eeb45d0e65558d76d98990fd0c37d25ffcf4073ab1f1722166", "s": "0b468c1c21bcf67512ba31a5f22e79c50eff3de81d88b7cea6289ea7a727b182"}, "jaunt.heldout:build_repair_feedback": {"p": "326957f89a7cb9d1db27a3701ae17be8977417480dc4eb56d18f68f1124bc007", "s": "4eb7f857b6dcd6af3107e59f5272a5bc11f6bd3696d7f640ab60ba4077db46c2"}, "jaunt.heldout:load_report": {"p": "065cce278be98b921a0325382f00989caca0297267af658cb9accb28b6d6b21a", "s": "286c1a62e00fe4412ba46b8941184b09f9c97e491ece4d192a1156ca52626373"}}
# jaunt:generation_fingerprint=sha256:ce5b7955d1d41de6dabe0fc8f7ef796a0c18cad9d8bcc9043d8e4bc2f8ce1306
# jaunt:module_api_digest=sha256:29a63f8cc44bb3e0285ee408984135d3c459aae651f417df32d0d05c7da7a24c
# jaunt:module_context_digest=sha256:a33a9b43981dde69d3e36231aac1570806c1cec71ffa382d48da0c9323b67834
# jaunt:spec_refs=["jaunt.heldout:assign_opaque_ids", "jaunt.heldout:build_repair_feedback", "jaunt.heldout:load_report"]

import json
from pathlib import Path


def assign_opaque_ids(report: dict) -> dict[str, str]:
    """Assign stable opaque identifiers to derived-tier test node IDs."""
    from jaunt.heldout import TIER_DERIVED, _item_records, _normalize_tier

    nodeids: set[str] = set()
    for record in _item_records(report):
        nodeid = record.get("nodeid")
        if isinstance(nodeid, str) and _normalize_tier(record.get("tier")) == TIER_DERIVED:
            nodeids.add(nodeid)
    return {
        nodeid: f"derived#{index}"
        for index, nodeid in enumerate(sorted(nodeids), start=1)
    }


def build_repair_feedback(report: dict, *, redact: bool = True) -> list[str]:
    """Build repair feedback, withholding held-out test details by default."""
    from jaunt.heldout import (
        TIER_EXAMPLE,
        _assert_no_derived_detail_leaks,
        _collection_error_records,
        _full_collection_feedback,
        _full_item_feedback,
        _item_records,
        _normalize_tier,
        _safe_exception_class,
        _string_or_empty,
    )

    opaque_ids = assign_opaque_ids(report)
    lines: list[str] = []
    emitted_derived: set[str] = set()

    for record in _item_records(report):
        if record.get("outcome") != "failed":
            continue

        if not redact:
            lines.extend(_full_item_feedback(record))
            continue

        tier = _normalize_tier(record.get("tier"))
        nodeid = _string_or_empty(record.get("nodeid"))
        if tier == TIER_EXAMPLE:
            lines.extend(_full_item_feedback(record))
            continue

        if nodeid in emitted_derived:
            continue
        emitted_derived.add(nodeid)
        opaque_id = opaque_ids.get(nodeid, "derived#unknown")
        exception_class = _safe_exception_class(record.get("exception_class"))
        lines.append(f"{opaque_id}: {exception_class}")

    for record in _collection_error_records(report):
        if not redact:
            lines.extend(_full_collection_feedback(record))
            continue

        module = _string_or_empty(record.get("module")) or "<unknown module>"
        exception_class = _safe_exception_class(record.get("exception_class"))
        lines.append(f"collection error in {module}: {exception_class}")

    if not lines:
        lines = ["tests failed; details withheld (held-out tier)"]

    if redact:
        _assert_no_derived_detail_leaks(report, lines)
    return lines


def load_report(path: str | Path) -> dict:
    """Load a held-out JSON report, returning an empty dict for unusable input."""
    try:
        text = Path(path).read_text(encoding="utf-8")
        if not text.strip():
            return {}
        report = json.loads(text)
    except (OSError, ValueError):
        return {}

    if not isinstance(report, dict):
        return {}
    return report
