# This file was generated by jaunt. DO NOT EDIT.
# jaunt:tool_version=1.5.1
# jaunt:kind=build
# jaunt:source_module=jaunt.heldout
# jaunt:module_digest=sha256:8c1b9c62a3abf2408b0d87bfd720bcbe85ddebc60b5dccb4dcd47f5d51ff38f5
# jaunt:digest_scheme=2
# jaunt:spec_digests={"jaunt.heldout:assign_opaque_ids": {"p": "57ef7511b6b708eeb45d0e65558d76d98990fd0c37d25ffcf4073ab1f1722166", "s": "0b468c1c21bcf67512ba31a5f22e79c50eff3de81d88b7cea6289ea7a727b182"}, "jaunt.heldout:build_repair_feedback": {"p": "326957f89a7cb9d1db27a3701ae17be8977417480dc4eb56d18f68f1124bc007", "s": "4eb7f857b6dcd6af3107e59f5272a5bc11f6bd3696d7f640ab60ba4077db46c2"}, "jaunt.heldout:load_report": {"p": "065cce278be98b921a0325382f00989caca0297267af658cb9accb28b6d6b21a", "s": "286c1a62e00fe4412ba46b8941184b09f9c97e491ece4d192a1156ca52626373"}}
# jaunt:generation_fingerprint=sha256:eb3e1333da7449bf778b85ba678bc29fcd75ee04d27ba64205e37fe6de578a45
# jaunt:module_api_digest=sha256:29a63f8cc44bb3e0285ee408984135d3c459aae651f417df32d0d05c7da7a24c
# jaunt:module_context_digest=sha256:a33a9b43981dde69d3e36231aac1570806c1cec71ffa382d48da0c9323b67834
# jaunt:spec_refs=["jaunt.heldout:assign_opaque_ids", "jaunt.heldout:build_repair_feedback", "jaunt.heldout:load_report"]

import importlib
import json
import sys
from pathlib import Path
from typing import Any


def _heldout_attr(name: str) -> Any:
    module = sys.modules.get("jaunt.heldout")
    if module is None:
        module = importlib.import_module("jaunt.heldout")
    return getattr(module, name)


def assign_opaque_ids(report: dict) -> dict[str, str]:
    """Assign stable ``derived#N`` identifiers to derived-tier item nodeids."""
    item_records = _heldout_attr("_item_records")
    normalize_tier = _heldout_attr("_normalize_tier")
    tier_derived = _heldout_attr("TIER_DERIVED")

    nodeids: set[str] = set()
    for record in item_records(report):
        nodeid = record.get("nodeid")
        if isinstance(nodeid, str) and normalize_tier(record.get("tier")) == tier_derived:
            nodeids.add(nodeid)

    return {nodeid: f"derived#{index}" for index, nodeid in enumerate(sorted(nodeids), 1)}


def build_repair_feedback(report: dict, *, redact: bool = True) -> list[str]:
    """Build human-readable repair feedback, redacting derived-tier detail by default."""
    item_records = _heldout_attr("_item_records")
    collection_error_records = _heldout_attr("_collection_error_records")
    full_item_feedback = _heldout_attr("_full_item_feedback")
    full_collection_feedback = _heldout_attr("_full_collection_feedback")
    normalize_tier = _heldout_attr("_normalize_tier")
    string_or_empty = _heldout_attr("_string_or_empty")
    safe_exception_class = _heldout_attr("_safe_exception_class")
    tier_example = _heldout_attr("TIER_EXAMPLE")

    opaque_ids = assign_opaque_ids(report)
    lines: list[str] = []
    emitted_derived: set[str] = set()

    for record in item_records(report):
        if record.get("outcome") != "failed":
            continue

        if not redact:
            lines.extend(full_item_feedback(record))
            continue

        tier = normalize_tier(record.get("tier"))
        nodeid = string_or_empty(record.get("nodeid"))
        if tier == tier_example:
            lines.extend(full_item_feedback(record))
            continue

        if nodeid in emitted_derived:
            continue
        emitted_derived.add(nodeid)
        opaque_id = opaque_ids.get(nodeid, "derived#unknown")
        exception_class = safe_exception_class(record.get("exception_class"))
        lines.append(f"{opaque_id}: {exception_class}")

    for record in collection_error_records(report):
        if not redact:
            lines.extend(full_collection_feedback(record))
            continue

        module = string_or_empty(record.get("module")) or "<unknown module>"
        exception_class = safe_exception_class(record.get("exception_class"))
        lines.append(f"collection error in {module}: {exception_class}")

    if not lines:
        lines = ["tests failed; details withheld (held-out tier)"]

    if redact:
        assert_no_derived_detail_leaks = _heldout_attr("_assert_no_derived_detail_leaks")
        assert_no_derived_detail_leaks(report, lines)

    return lines


def load_report(path: str | Path) -> dict:
    """Load a held-out JSON report from ``path``, returning ``{}`` for unusable input."""
    try:
        text = Path(path).read_text(encoding="utf-8")
        if not text.strip():
            return {}
        parsed = json.loads(text)
    except (OSError, ValueError):
        return {}

    if not isinstance(parsed, dict):
        return {}
    return parsed
