# This file was generated by jaunt. DO NOT EDIT.
# jaunt:tool_version=1.6.3
# jaunt:kind=build
# jaunt:source_module=jaunt.migrate
# jaunt:module_digest=sha256:7920839f5c541ab390aa6c75c5e938c32d4924c7298e5fc18623dee5247df742
# jaunt:digest_scheme=2
# jaunt:spec_digests={"jaunt.migrate:apply_stub_rewrite": {"p": "382a39998538aeebba13d27938f7b38cf43ad51e711ef748ac22bf92374f154e", "s": "805dad50e800ac1e579cdce49c9059f2fbdf654d3074bbf48d768c9dbde2bff2"}, "jaunt.migrate:plan_legacy_stub_rewrites": {"p": "cabe9ac07283424a31b25ce9bba84f1c632aa91a77016dd3b0716df1f6873f5f", "s": "38c7f5ff955c1baefc047a31c7e9ae445945666aca5cb3d583814e89a736f1f2"}, "jaunt.migrate:plan_stub_reemissions": {"p": "b47a3f9a02a85fe6bebeece743c5c5cf374acabc961dcc01ba5134b3a934c16a", "s": "f18a1d1f6b8f6e3ce6e09ebdbf8a236275dc2c20de982bc49bf6040a5c736134"}}
# jaunt:generation_fingerprint=sha256:ce5b7955d1d41de6dabe0fc8f7ef796a0c18cad9d8bcc9043d8e4bc2f8ce1306
# jaunt:module_api_digest=sha256:562eee48dabc5d6ad1bebe971db3627f440f3bf5e23010ed08a8b86af3304bef
# jaunt:module_context_digest=sha256:571e12db69fc0fdc575b35a5c7cdfc3e9a8011e72ccd83c4ddd1aef9c9a81128
# jaunt:spec_refs=["jaunt.migrate:apply_stub_rewrite", "jaunt.migrate:plan_legacy_stub_rewrites", "jaunt.migrate:plan_stub_reemissions"]

from __future__ import annotations

import ast
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from jaunt.migrate import MigrationAction

__all__ = ["apply_stub_rewrite", "plan_legacy_stub_rewrites", "plan_stub_reemissions"]


def apply_stub_rewrite(action: MigrationAction) -> None:
    """Replace the named legacy stub's raise statement with an ellipsis."""
    from jaunt import migrate

    with action.path.open("r", encoding="utf-8", newline="") as source_handle:
        source = source_handle.read()

    tree = ast.parse(source, filename=str(action.path))
    targets = [
        migrate._stub_raise(node)
        for symbol, node in migrate._iter_rewritable_nodes(tree)
        if symbol == action.symbol
    ]
    if not targets:
        return

    lines = source.splitlines(keepends=True)
    for raise_node in sorted(targets, key=lambda node: node.lineno, reverse=True):
        start = raise_node.lineno - 1
        end = raise_node.end_lineno or raise_node.lineno
        original_line = lines[start]
        ending = migrate._line_ending(original_line)
        line_content = original_line[: -len(ending)] if ending else original_line
        indentation = line_content[: len(line_content) - len(line_content.lstrip())]
        lines[start:end] = [f"{indentation}...{ending}"]

    with action.path.open("w", encoding="utf-8", newline="") as source_handle:
        source_handle.write("".join(lines))


def plan_legacy_stub_rewrites(
    *, source_file: Path, module: str, governed_symbols: set[str]
) -> list[MigrationAction]:
    """Plan legacy stub-body rewrites for one source file."""
    from jaunt import migrate

    source = source_file.read_text(encoding="utf-8")
    tree = ast.parse(source, filename=str(source_file))
    actions: list[MigrationAction] = []

    for symbol, _node in migrate._iter_rewritable_nodes(tree):
        governed = migrate._symbol_is_governed(symbol, governed_symbols)
        classification = "re-stamp" if governed else "newly-governs"
        label = "re-stamp (free)" if governed else "newly-governs"
        actions.append(
            migrate.MigrationAction(
                migration_id=migrate.LEGACY_STUB_MIGRATION_ID,
                path=source_file,
                module=module,
                symbol=symbol,
                kind="rewrite-stub-body",
                classification=classification,
                description=(
                    f"{module}.{symbol}: raise RuntimeError('spec stub') -> ... [{label}]"
                ),
            )
        )

    return actions


def plan_stub_reemissions(
    *, module_specs: dict[str, list], package_dir: Path, generated_dir: str
) -> list[MigrationAction]:
    """Plan re-emission of stale generated stubs."""
    from jaunt import builder, stub_emitter
    from jaunt import migrate

    actions: list[MigrationAction] = []
    for module in sorted(module_specs):
        entries = module_specs[module]
        if not entries:
            continue

        generated_source = builder._read_generated(package_dir, generated_dir, module)
        if generated_source is None:
            continue

        source_file = entries[0].source_file
        staleness = stub_emitter.stub_staleness(
            source_file=source_file,
            generated_source=generated_source,
        )
        if staleness is None:
            continue

        actions.append(
            migrate.MigrationAction(
                migration_id=migrate.STUB_REEMIT_MIGRATION_ID,
                path=stub_emitter.stub_path_for_source(source_file),
                module=module,
                symbol="",
                kind="reemit-stub",
                classification="re-stamp",
                description=(
                    f"{module}: re-emit .pyi stub (format/version drift) [re-stamp (free)]"
                ),
            )
        )

    return actions
