# This file was generated by jaunt. DO NOT EDIT.
# jaunt:tool_version=1.5.1
# jaunt:kind=build
# jaunt:source_module=jaunt.migrate
# jaunt:module_digest=sha256:7920839f5c541ab390aa6c75c5e938c32d4924c7298e5fc18623dee5247df742
# jaunt:digest_scheme=2
# jaunt:spec_digests={"jaunt.migrate:apply_stub_rewrite": {"p": "382a39998538aeebba13d27938f7b38cf43ad51e711ef748ac22bf92374f154e", "s": "805dad50e800ac1e579cdce49c9059f2fbdf654d3074bbf48d768c9dbde2bff2"}, "jaunt.migrate:plan_legacy_stub_rewrites": {"p": "cabe9ac07283424a31b25ce9bba84f1c632aa91a77016dd3b0716df1f6873f5f", "s": "38c7f5ff955c1baefc047a31c7e9ae445945666aca5cb3d583814e89a736f1f2"}, "jaunt.migrate:plan_stub_reemissions": {"p": "b47a3f9a02a85fe6bebeece743c5c5cf374acabc961dcc01ba5134b3a934c16a", "s": "f18a1d1f6b8f6e3ce6e09ebdbf8a236275dc2c20de982bc49bf6040a5c736134"}}
# jaunt:generation_fingerprint=sha256:eb3e1333da7449bf778b85ba678bc29fcd75ee04d27ba64205e37fe6de578a45
# jaunt:module_api_digest=sha256:562eee48dabc5d6ad1bebe971db3627f440f3bf5e23010ed08a8b86af3304bef
# jaunt:module_context_digest=sha256:571e12db69fc0fdc575b35a5c7cdfc3e9a8011e72ccd83c4ddd1aef9c9a81128
# jaunt:spec_refs=["jaunt.migrate:apply_stub_rewrite", "jaunt.migrate:plan_legacy_stub_rewrites", "jaunt.migrate:plan_stub_reemissions"]

from __future__ import annotations

import ast
from pathlib import Path
from typing import TYPE_CHECKING, Literal

if TYPE_CHECKING:
    from jaunt.migrate import MigrationAction


def apply_stub_rewrite(action: MigrationAction) -> None:
    """Rewrite exactly the one legacy stub body named by ``action`` to ``...``."""
    from jaunt import migrate as source_migrate

    with action.path.open("r", encoding="utf-8", newline="") as file:
        source = file.read()

    tree = ast.parse(source, filename=str(action.path))
    targets: list[ast.Raise] = [
        source_migrate._stub_raise(node)
        for symbol, node in source_migrate._iter_rewritable_nodes(tree)
        if symbol == action.symbol
    ]
    if not targets:
        return

    lines = source.splitlines(keepends=True)
    for raise_node in sorted(targets, key=lambda node: node.lineno, reverse=True):
        start = raise_node.lineno - 1
        end = raise_node.end_lineno or raise_node.lineno
        original_line = lines[start]
        ending = source_migrate._line_ending(original_line)
        content = original_line[: -len(ending)] if ending else original_line
        indent = content[: len(content) - len(content.lstrip())]
        lines[start:end] = [f"{indent}...{ending}"]

    with action.path.open("w", encoding="utf-8", newline="") as file:
        file.write("".join(lines))


def plan_legacy_stub_rewrites(
    *, source_file: Path, module: str, governed_symbols: set[str]
) -> list[MigrationAction]:
    """Plan legacy ``raise RuntimeError("spec stub")`` bodies for ellipsis rewrites."""
    from jaunt import migrate as source_migrate

    source = source_file.read_text(encoding="utf-8")
    tree = ast.parse(source, filename=str(source_file))
    actions: list[MigrationAction] = []

    for symbol, node in source_migrate._iter_rewritable_nodes(tree):
        classification: Literal["re-stamp", "newly-governs"]
        if source_migrate._symbol_is_governed(symbol, governed_symbols):
            classification = "re-stamp"
            label = "re-stamp (free)"
        else:
            classification = "newly-governs"
            label = "newly-governs"

        actions.append(
            source_migrate.MigrationAction(
                migration_id=source_migrate.LEGACY_STUB_MIGRATION_ID,
                path=source_file,
                module=module,
                symbol=symbol,
                kind="rewrite-stub-body",
                classification=classification,
                description=(
                    f"{module}.{symbol}: raise RuntimeError('spec stub') -> ... [{label}]"
                ),
            )
        )

    return actions


def plan_stub_reemissions(
    *, module_specs: dict[str, list], package_dir: Path, generated_dir: str
) -> list[MigrationAction]:
    """Plan stale generated ``.pyi`` stubs for re-emission."""
    from jaunt import builder, migrate as source_migrate, stub_emitter

    actions: list[MigrationAction] = []

    for module in sorted(module_specs):
        entries = module_specs[module]
        if not entries:
            continue

        gen_source = builder._read_generated(package_dir, generated_dir, module)
        if gen_source is None:
            continue

        source_file = entries[0].source_file
        staleness = stub_emitter.stub_staleness(
            source_file=source_file,
            generated_source=gen_source,
        )
        if staleness is None:
            continue

        actions.append(
            source_migrate.MigrationAction(
                migration_id=source_migrate.STUB_REEMIT_MIGRATION_ID,
                path=stub_emitter.stub_path_for_source(source_file),
                module=module,
                symbol="",
                kind="reemit-stub",
                classification="re-stamp",
                description=(
                    f"{module}: re-emit .pyi stub "
                    "(format/version drift) [re-stamp (free)]"
                ),
            )
        )

    return actions
