# This .pyi stub was generated by jaunt. DO NOT EDIT.
# jaunt:tool_version=1.5.1
# jaunt:kind=stub
# jaunt:source_module=jaunt.contract.cases
# jaunt:generated_digest=sha256:b35275c3015fa7be4bd7545db723c1d8409c229b42e2e3124f7b891416c90ce6
# jaunt:inputs_digest=sha256:9c4d77bda00ef9dee839b98292b5dcc3aed7944758354b145e9f4615b5db0435

import ast
import builtins
import re
from dataclasses import dataclass, field
from typing import TypedDict

_HEADER_RE = re.compile("([A-Za-z][A-Za-z ]*):\\s*$")

_CASE_EXCEPTION_NAME_RE = re.compile("^[A-Za-z_][A-Za-z0-9_]*$")

_FIXTURES_RE = re.compile("^Fixtures:\\s*(.+)$", re.MULTILINE)

_BUILTIN_NAMES = frozenset(dir(builtins))

class _MakeCaseKw(TypedDict):
    target: str
    async_map: dict[str, bool]
    fixtures_declared: tuple[str, ...]
    module_names: frozenset[str]
    method_override: str | None

class CaseParseError(ValueError):
    line: str

    def __init__(self, message: str, *, line: str) -> None: ...

@dataclass(frozen=True, slots=True)
class CallCase:
    source_line: str
    call_expr: str
    expected_expr: str | None
    exc_name: str | None
    fixtures: tuple[str, ...]
    imports: tuple[str, ...]
    is_async: bool
    legacy: bool
    method: str | None

@dataclass(frozen=True, slots=True)
class CaseBlocks:
    examples: tuple[CallCase, ...] = ()
    raises: tuple[CallCase, ...] = ()
    fixtures_declared: tuple[str, ...] = field(default=())

    def is_empty(self) -> bool: ...
    def has_fixture_cases(self) -> bool: ...
    def merged(self, other: CaseBlocks) -> CaseBlocks: ...

def _case_lines_for_section(docstring: str, name: str) -> list[str]: ...
def _parse_fixtures(docstring: str) -> tuple[str, ...]: ...
def _valid_case_expr(text: str) -> bool: ...
def _call_root_and_method(expr: ast.expr, target: str) -> tuple[bool, str | None]: ...
def _target_names(target: ast.AST) -> set[str]: ...
def _lambda_arg_names(args: ast.arguments) -> set[str]: ...
def _bound_names_in_expr(tree: ast.AST) -> set[str]: ...
def _names_in(expr: str) -> set[str]: ...
def _classify_names(
    *,
    source_line: str,
    exprs: list[str],
    target: str,
    fixtures_declared: tuple[str, ...],
    module_names: frozenset[str],
) -> tuple[tuple[str, ...], tuple[str, ...]]: ...
def _is_async_call(call_expr: str, *, target: str, async_map: dict[str, bool]) -> bool: ...
def _make_case(
    *,
    source_line: str,
    call_expr: str,
    expected_expr: str | None,
    exc_name: str | None,
    legacy: bool,
    target: str,
    async_map: dict[str, bool],
    fixtures_declared: tuple[str, ...],
    module_names: frozenset[str],
    method_override: str | None,
) -> CallCase: ...
def _split_top_level_eq(line: str) -> tuple[str, str] | None: ...
def parse_case_blocks(
    docstring: str,
    *,
    target: str,
    async_map: dict[str, bool],
    module_names: frozenset[str],
    method: str | None = None,
) -> CaseBlocks: ...
