# This .pyi stub was generated by jaunt. DO NOT EDIT.
# jaunt:tool_version=1.5.1
# jaunt:kind=stub
# jaunt:source_module=jaunt.contract.drift
# jaunt:generated_digest=sha256:54c84b3904a5f1f6812f3c5dffcd63348128fb0ae09f0e4c188742a4f194197b
# jaunt:inputs_digest=sha256:1508dc5ae6f2002d7efa0e6af2b7ff252836fe5135837577e0abeceac9677d30

import enum

class DriftState(enum.Enum):
    UNBUILT = "unbuilt"
    STALE_PROSE = "stale-prose"
    SIGNATURE_DRIFT = "signature-drift"
    BEHAVIOR_DRIFT = "behavior-drift"
    REFACTORED = "refactored"
    IN_SYNC = "in-sync"

_BLOCKING = frozenset(
    {
        DriftState.UNBUILT,
        DriftState.STALE_PROSE,
        DriftState.SIGNATURE_DRIFT,
        DriftState.BEHAVIOR_DRIFT,
    }
)

BLOCKING_MESSAGE: dict[DriftState, str] = {
    DriftState.UNBUILT: "no contract battery; run `jaunt reconcile`.",
    DriftState.STALE_PROSE: "contract prose changed; run `jaunt reconcile`.",
    DriftState.SIGNATURE_DRIFT: "signature changed; run `jaunt reconcile`.",
    DriftState.BEHAVIOR_DRIFT: "body no longer satisfies the contract; fix the body or reconcile.",
}

def is_blocking(state: DriftState) -> bool: ...
def compute_drift_state(
    *,
    has_battery: bool,
    prose_match: bool,
    signature_match: bool,
    body_match: bool,
    battery_passed: bool | None,
) -> DriftState: ...
