# This .pyi stub was generated by jaunt. DO NOT EDIT.
# jaunt:tool_version=1.6.3
# jaunt:kind=stub
# jaunt:source_module=jaunt.contract.drift
# jaunt:generated_digest=sha256:c34c920ca1b0ddd76ce02330c8601352cfbb4d44fb9f3f144dfcf29050549793
# jaunt:inputs_digest=sha256:a4b87294f6b5dd5defa0844c3a5289559bb521ac54931020672f483c54fd7ac0

import enum

class DriftState(enum.Enum):
    UNBUILT = "unbuilt"
    STALE_PROSE = "stale-prose"
    SIGNATURE_DRIFT = "signature-drift"
    BEHAVIOR_DRIFT = "behavior-drift"
    REFACTORED = "refactored"
    IN_SYNC = "in-sync"

_BLOCKING = frozenset(
    {
        DriftState.UNBUILT,
        DriftState.STALE_PROSE,
        DriftState.SIGNATURE_DRIFT,
        DriftState.BEHAVIOR_DRIFT,
    }
)

BLOCKING_MESSAGE: dict[DriftState, str] = {
    DriftState.UNBUILT: "no contract battery; run `jaunt reconcile`.",
    DriftState.STALE_PROSE: "contract prose changed; run `jaunt reconcile`.",
    DriftState.SIGNATURE_DRIFT: "signature changed; run `jaunt reconcile`.",
    DriftState.BEHAVIOR_DRIFT: "body no longer satisfies the contract; fix the body or reconcile.",
}

def is_blocking(state: DriftState) -> bool: ...
def compute_drift_state(
    *,
    has_battery: bool,
    prose_match: bool,
    signature_match: bool,
    body_match: bool,
    battery_passed: bool | None,
) -> DriftState: ...
