# This .pyi stub was generated by jaunt. DO NOT EDIT.
# jaunt:tool_version=1.7.0
# jaunt:kind=stub
# jaunt:source_module=jaunt.contract.edits
# jaunt:generated_digest=sha256:c8c85f6c5131d13f4f51aeacd1674704064e812cd1279c038bc70340cc8b2ae2
# jaunt:inputs_digest=sha256:dba63e2d5e662480e177f7fefdb97cbde607e34115d61c454e9d4f1226de810b

import ast

def _find_target(
    source: str, name: str
) -> ast.FunctionDef | ast.AsyncFunctionDef | ast.ClassDef: ...
def _ensure_import_jaunt(lines: list[str]) -> list[str]: ...
def add_contract_marker(source: str, func_name: str) -> str: ...
def remove_contract_marker(source: str, func_name: str) -> str: ...
