# This .pyi stub was generated by jaunt. DO NOT EDIT.
# jaunt:tool_version=1.7.2
# jaunt:kind=stub
# jaunt:source_module=jaunt.contract.edits
# jaunt:generated_digest=sha256:c8c85f6c5131d13f4f51aeacd1674704064e812cd1279c038bc70340cc8b2ae2
# jaunt:inputs_digest=sha256:8f0183665a7f653564af20bba8f525bfddeaa8d032d4f5f0db967146568a638b
# jaunt:rendered_digest=sha256:0bc19a0f0b5791a5c3d658a1f03eea145c16748be96c76999c69bd22184a110d

import ast

def _find_target(
    source: str, name: str
) -> ast.FunctionDef | ast.AsyncFunctionDef | ast.ClassDef: ...
def _ensure_import_jaunt(lines: list[str]) -> list[str]: ...
def add_contract_marker(source: str, func_name: str) -> str: ...
def remove_contract_marker(source: str, func_name: str) -> str: ...
