# This .pyi stub was generated by jaunt. DO NOT EDIT.
# jaunt:tool_version=1.5.1
# jaunt:kind=stub
# jaunt:source_module=jaunt.contract.edits
# jaunt:generated_digest=sha256:3fe5b9cc349959958a8c4a21de2870bcdd1d1fd994559f18a1e35f5cdb701430
# jaunt:inputs_digest=sha256:6862e744863e5bba1b7414eb839daa0287c65ee31b7215f053b07442a6137c4a

import ast

def _find_target(
    source: str, name: str
) -> ast.FunctionDef | ast.AsyncFunctionDef | ast.ClassDef: ...
def _ensure_import_jaunt(lines: list[str]) -> list[str]: ...
def add_contract_marker(source: str, func_name: str) -> str: ...
def remove_contract_marker(source: str, func_name: str) -> str: ...
