# This .pyi stub was generated by jaunt. DO NOT EDIT.
# jaunt:tool_version=1.7.2
# jaunt:kind=stub
# jaunt:source_module=jaunt.contract.strength
# jaunt:generated_digest=sha256:9f6644b91d1158f1775d74e683a6a03f991133c4ada581b4b9ae1b99547903d4
# jaunt:inputs_digest=sha256:2e330d673b079c1af6ccfd3ea0b7a0555e9c0179f328b29f3da2f214bdb2b09f
# jaunt:rendered_digest=sha256:69262ce229a83aaae453f7cf3016fddcc933d08dfa9e301b9275a1037d7f26e1

import ast
from collections.abc import Iterator

from jaunt.contract.cases import CaseBlocks

EJECT_STRENGTH_WARN = 0.5

def parse_strength(text: str) -> tuple[int, int]: ...

_CMP_SWAP: dict[type[ast.cmpop], type[ast.cmpop]] = {
    ast.Lt: ast.LtE,
    ast.LtE: ast.Lt,
    ast.Gt: ast.GtE,
    ast.GtE: ast.Gt,
    ast.Eq: ast.NotEq,
    ast.NotEq: ast.Eq,
}

_BINOP_SWAP: dict[type[ast.operator], type[ast.operator]] = {
    ast.Add: ast.Sub,
    ast.Sub: ast.Add,
    ast.Mult: ast.Div,
    ast.Div: ast.Mult,
}

_BOOL_SWAP: dict[type[ast.boolop], type[ast.boolop]] = {ast.And: ast.Or, ast.Or: ast.And}

def _mutation_targets(tree: ast.Module) -> list[ast.AST]: ...
def _skip_constant_ids(tree: ast.Module) -> set[int]: ...
def _stmt_deletion_targets(tree: ast.Module) -> list[tuple[int, int]]: ...
def _emit_stmt_deletion(base: ast.Module, walk_index: int, stmt_index: int) -> str | None: ...
def iter_mutants(func_source: str) -> Iterator[str]: ...
def _emit(base: ast.Module, i: int, transform) -> str | None: ...
def _mutate_node(base: ast.Module, i: int, node: ast.AST, skip: set[int]) -> Iterator[str]: ...
def _swap_cmp(t: ast.AST) -> bool: ...
def _swap_bool(t: ast.AST) -> bool: ...
def _swap_binop(t: ast.AST) -> bool: ...
def _mutate_const(t: ast.AST) -> bool: ...
def _default_return(t: ast.AST) -> bool: ...
def format_strength(killed: int, applicable: int) -> str: ...

_MUTANT_EVAL_TIMEOUT_S: float = 2.0

def _evaluate_mutant_killed(pure: CaseBlocks, ns: dict[str, object]) -> bool: ...
def compute_case_strength(
    source: str, target: str, blocks: CaseBlocks, namespace: dict[str, object]
) -> tuple[int, int, int]: ...
