/**
 * Minimal stand-in for the `jaunt` npm package's runtime surface.
 *
 * In the real port this is essentially all `jaunt` ships at runtime: inert
 * markers plus a throwing placeholder. Everything interesting happens
 * statically (the scanner reads these calls out of the AST; the type checker
 * resolves deps and enforces signatures) or at resolve time (see
 * ./register.mjs). No user code ever runs during discovery — that is the
 * port's one governing principle.
 */

/** Per-spec options carried inside the `magic()` stub-body call. */
export interface MagicOptions {
  /**
   * Explicit dependency edges. These are real identifiers, so the checker
   * resolves them exactly and renames refactor them — unlike the Python
   * port's string/object hybrid.
   */
  readonly deps?: readonly unknown[];
  /** Extra guidance appended to this spec's build prompt. */
  readonly prompt?: string;
}

/** Module-level defaults, merged key-by-key into every governed spec. */
export interface MagicModuleOptions {
  readonly deps?: readonly unknown[];
  readonly prompt?: string;
  readonly inferDeps?: boolean;
  /** Opt this module's specs into implicit generated test coverage. */
  readonly test?: boolean;
}

/** Thrown when a spec stub is executed at runtime. */
export class JauntNotBuiltError extends Error {
  constructor(detail?: string) {
    super(
      "jaunt spec stub called at runtime — spec modules (*.jaunt.ts) are " +
        "build inputs, never runtime imports. Import the module's public " +
        "facade (./index.ts) instead, and run `jaunt build` if it reports " +
        "a missing __generated__ implementation" +
        (detail === undefined ? "" : `: ${detail}`),
    );
    this.name = "JauntNotBuiltError";
  }
}

/**
 * Governs every top-level export below it, mirroring Python's
 * `jaunt.magic_module(__name__)` — the primary authoring style, and in TS
 * the only one, since TC39 decorators cannot decorate plain functions.
 * A runtime no-op; the scanner detects the call statically.
 */
export function magicModule(_options?: MagicModuleOptions): void {}

/**
 * The canonical spec stub body: `return jaunt.magic()` (or a bare
 * `jaunt.magic()` statement in a `void` function). Returns `never`, so one
 * form typechecks against any declared return type, and calling an unbuilt
 * spec throws a helpful error — Python's placeholder semantics for free.
 */
export function magic(_options?: MagicOptions): never {
  throw new JauntNotBuiltError();
}

/** The canonical test-spec stub body (for files under `test_roots`). */
export function testSpec(_options?: {
  readonly targets?: readonly unknown[];
  readonly prompt?: string;
}): never {
  throw new JauntNotBuiltError("test specs are generated by `jaunt test`");
}

// Note on markers that did NOT survive the design review:
// - `@jaunt.sig` — gone; declared signatures are checker-enforced by
//   default via authored-type-annotated exports (see
//   src/tokens/__generated__/impl.ts), so the sealed/guidepost distinction
//   dissolves.
// - `preserve` as a decorator — gone; native Node type-stripping rejects
//   decorator syntax, so the rare "real method whose body looks like a
//   stub" corner is marked with a `@jauntPreserve` TSDoc tag instead
//   (fully erasable, statically scanned like everything else).
